<script>
  import { base } from '$app/paths';
  import { onMount } from 'svelte';

  // Live workspace status, generated by the `focus_forge_status` crate into
  // site/static/status.json (served at /status.json). We fetch it at load so the
  // section reflects the real repo — crates, labs, test counts, phase/chapter —
  // instead of hardcoded text. Refresh it by running:
  //   cargo run -p focus_forge_status
  let status = $state(null);
  let failed = $state(false);

  onMount(async () => {
    try {
      const res = await fetch(`${base}/status.json`);
      if (!res.ok) throw new Error(`status ${res.status}`);
      status = await res.json();
    } catch {
      failed = true;
    }
  });

  // Derived views. $derived recomputes whenever `status` changes.
  const crates = $derived(status ? status.crates.filter((c) => c.kind === 'crate') : []);
  const labs = $derived(status ? status.crates.filter((c) => c.kind === 'lab') : []);
  const totalPassed = $derived(
    status ? status.crates.reduce((sum, c) => sum + c.tests_passed, 0) : 0
  );
  const anyFailing = $derived(status ? status.crates.some((c) => c.tests_failed > 0) : false);
  const shortHash = $derived(status ? status.last_commit.hash.slice(0, 7) : '');
  const commitDate = $derived(status ? status.last_commit.date.slice(0, 10) : '');
</script>

<section id="status">
  <h2>Where the course is now</h2>
  <p class="sub">
    Live from the repository — crates, labs, and test counts generated by the
    <code class="inline">focus_forge_status</code> tool. Not hand-maintained.
  </p>

  {#if status}
    <div class="status-summary">
      <span class="pill {anyFailing ? '' : 'on'}">
        {anyFailing ? '⚠ some tests failing' : `✓ ${totalPassed} tests passing`}
      </span>
      <span class="pill next">Phase {status.phase} · {status.phase_name}</span>
      <span class="pill">Now: {status.chapter} — {status.chapter_name}</span>
    </div>

    <h3 class="group-label">Product crates</h3>
    <div class="grid cols-3">
      {#each crates as c (c.name)}
        <div class="card status-card">
          <span class="pill {c.tests_failed > 0 ? '' : 'on'} count-pill">
            {c.tests_failed > 0 ? `${c.tests_failed} failing` : `${c.tests_passed} ✓`}
          </span>
          <h3>{c.name}</h3>
          <p>{c.tests_passed} tests{c.tests_failed > 0 ? `, ${c.tests_failed} failing` : ''}</p>
        </div>
      {/each}
    </div>

    <h3 class="group-label">Chapter labs</h3>
    <div class="grid cols-3">
      {#each labs as c (c.name)}
        <div class="card status-card">
          <span class="pill {c.tests_failed > 0 ? '' : 'on'} count-pill">
            {c.tests_failed > 0 ? `${c.tests_failed} failing` : `${c.tests_passed} ✓`}
          </span>
          <h3>{c.name}</h3>
          <p>{c.tests_passed} tests{c.tests_failed > 0 ? `, ${c.tests_failed} failing` : ''}</p>
        </div>
      {/each}
    </div>

    <p class="status-meta">
      Last commit <code class="inline">{shortHash}</code> · {commitDate} · snapshot {status.generated_at.slice(0, 10)}
    </p>
  {:else if failed}
    <!-- The page must never break if the snapshot is missing. -->
    <div class="pills">
      <span class="pill on">✓ Chapter 0 — setup lab</span>
      <span class="pill on">✓ focus_forge_core — domain crate</span>
      <span class="pill on">✓ focus_forge_cli — command-line app</span>
      <span class="pill">Live status snapshot unavailable</span>
    </div>
  {:else}
    <p class="sub" aria-busy="true">Loading live status…</p>
  {/if}
</section>

<style>
  .status-summary {
    display: flex;
    flex-wrap: wrap;
    gap: 10px;
    margin-bottom: 28px;
  }
  .group-label {
    font-size: 14px;
    text-transform: uppercase;
    letter-spacing: 0.04em;
    color: var(--muted);
    margin: 26px 0 12px;
  }
  .status-card {
    position: relative;
  }
  .status-card h3 {
    margin: 0 0 4px;
    font-size: 15.5px;
    font-family: 'SF Mono', 'JetBrains Mono', 'Fira Code', Consolas, Menlo, monospace;
    color: var(--rust-ink);
  }
  .count-pill {
    position: absolute;
    top: 16px;
    right: 16px;
    font-size: 12px;
  }
  .status-meta {
    color: var(--muted);
    font-size: 13.5px;
    margin: 26px 0 0;
  }
</style>
